---
title: "chemicals_research_eu"
author: "Richard Pham"
date: "April 5, 2018"
output: github_document
---

Please refer to link : `Parameters.doc` 

Below is an overview of what makes water quality, by European water standards, standards 
that we should at least look at, if not adhere to : 

*please note : the word usage is synonymous with origin in some cases*


*please note : for any variables below we will use to measure water quality, we should be sure to first look at average or safe concentrations, detailed at the end of each variable's description in the referred link* 

*please note : if link does not show any I/PV value for any interesting variables, we should not factor it into water quality* 

__Aluminum__ : negative  

- effects : pose danger to persons suffering from kidney disorders, and 
            causes neurological disorders 

- usage :
  the compound aluminium sulphate ("alum") is very widely used in
  water treatment to remove colour and non-filtrable matter in raw
  waters.

- metrics : recommended levels around 

__Ammonia__ : indicator  

- effects : indicates possibility of sewage pollution and consequent 
            possible presence of pathogenic micro-organisms
 
- usage : N/A 

- metrics : used in conjunction with chloride, because both are present
            in significant quantities in sewage.
            typical levels around 0.3 mg/L (limiting amount)

__Antimony__ : indicator 

- effects : indicaates possible pollution from metal industry 

- usage : naturally occurring trace element used in metal industry and in
          flame retardant materials. 

- metrics : typical level around 1 ug/L 

__Barium__ : negative 

- effects : excessive amounts can cause muscular, cardiovascular, and 
            renal damage. 

- usage : naturally occuring minium 

- metric : 0.7 mg/l 

__Benzene__ : negative 

- effects : carcinogenic substance that also affects central nervous 
            system 

- usage : emission from motor vehicles mainly 

__Benzoapyrene__ : negative 

- effects : carcinogenic and mutagenic substance considered to be highly 
            undesirable in drinking water, main exposure is through 
            food.

- usage : synthetic complete aromatic organic compound formed by 
          combustion of organic materials.  

__Beryllium__ : negative 

- effects : toxic if inhaled, and can lead to variety of respiratory and 
            other diseases. 

- usage : used in brass and alloys, particularly by aircraft and space 
          industries

__Boron__ : negative 

- effects : excessive amounts of boron can cause nervous problems 

- usage : naturally occurring trace element used in cleaning compounds 
          and alloys 

- metric : typical is 5 mg/L w.r.t. seawater 

__Bromate__ : negative  

- effects : carcinogenic and mutagenic (dafuqq is the diff?)

- usage : occurs when bromide present in water oxidized by agents, particularly **chloride**

__Cadmium__ : negative 

- effects : highly toxic, severe restricutions on its concentratios in 
            water; causes bone damage, chronic kidney disease, cancer, 
            and hypertension. 

- usage : strongly absorbed in muds, humus and organic matter, entry 
          into food chain via fish 

__Calcium__ : positive 

- effects : occurs in rocks, bones, shells; healthy 

- usage : existence 

__Carbon_Dioxide__ : indicator 

- effects : n/a  

- usage : air, algal respiration; high levels enhances the effects of deoxygenation of high ammonia concentrations; excessive levels of carbon dioxide may have effects on aquatic life 

- personal comment : have to take this into account when looking at 
                     ammonia and fish levels if used for measuring water
                     quality 

__Chloride__ : indicator 

- effects : no real risks, but high levels increase probability of 
            pollution (sewers have more chloride)

- usage : naturally occurring in waters

__Chlorophyll__ : indicator 

- effects : no real effects 

- usage : naturally-occurring green pigment in algae, cyanobacteria, 
            plants, vegetation 

- personal comment : indicates higher level of vegetation (what does 
                     vegetation do to quality?) 

__Chromium__ : negative 

- effects : toxic, but depends on the form it exists in 

- usage : naturally occurs in ore, but is also discharged from 
          electroplating, tanning, textil, paint and dyeing plants. 

- personal comment : be cautious when using this as a measure, be sure 
                     that chromium form fits relative levels


__Clostridium_Perfringens__ : negative 

- effects : a fungus, some species are pathogenic, but health issues might be related to toxins released by fungus instead of fungus itself. 

- usage : human and animal wastes and/or soil 

- personal comment : spores can survive in water longer on average than 
                     other fungi, resistant to disinfection


__Coliforms__ : indicator 

- effects : increases the likelihood of pathogens 
- usage : present in human/animal waste 

__Color__ : indicator 

- effects : indicates the type of biology present in water
            more for aesthetic purposes 

__Copper__ : indicator 

- effects : not particularly toxic to human beings, but may reduce 
            quality of taste in high concentrations  
- usage : ores and industrial wastes 

__Cryptosporidium__ : negative 

- effects : parasite with pathogenic effects on human beings, weakens 
            immune systems 

- usage : present in human and animal wastes 

__Cyanide__ : 

- effects : extremely toxic,, in excessive amounts 

- usage : indistrial effluents 

__Enterococci__ : 

- effects : some members of this group have pathogenic properties 

- usage : sewage and wastes 


-----------------------------------------------
From here on, only the names and effects of particularly interesting 
variables will be displayed (typing is a waste) : 


__Fluoride__ : negative (in high conc.)  
high concentrations lead to rotting of teeth 

__Heavy_Metals__ : negative 
includes such as : 
antimony, cobalt, nickel (refer to pg. 59, #37) 

- effects : toxic to humans  


__Hydrocarbons__ : depends 

__Lead__ : negative 

- effects : toxic, cumulative poisoning 

__Mercury__ : negative 

- effects : extremely negatively effective 

__Nickel__ : ambiguous 

- effects : toxic to fish, questionable for human beings 

__Nitrate__ : negative (to infants) 


__Nitrogen__ : indicator  

- effects : indicates purity of water 

__Oxidisability__ : indicator 

- effects : indicates purity of water 

__Oxygen_Demand_Biochemical__ : indicator 

- effects : indicates purity of water 

__Oxygen_dissolved__ : indicator 

- effects : indicates purity of water 


__Pesticides__ : negative 

__ pH__ : indicator 

- effects : value indicates acidicity/alkalinity, with organoeleptic consequence 

__Phosphorus__ : indicator 

- effects : indicates overall water quality 

__Pseudomonas_Aueruginosa__ : negative 

- effects : any existing concentration increases eye/ear infections 

__Salmonella__ : negative 

- effects : for instance, typhoid fever


__Selenium__ : negative 

- effects : toxic element except in trace conc. 

__Silicon__ : negative 

__Sodium__ : negative (in excess) 

- effects : hypertension 






